on: [push]
name: Linux_Container_Workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2
      
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Build and push Docker image
        run: |
          az acr login --name haritha123
          docker build -f .github/workflows/Dockerfile -t haritha123.azurecr.io/hello-world-app:v111 .github/workflows
          docker push haritha123.azurecr.io/hello-world-app:v111
          docker build -f mongodb/Dockerfile -t haritha123.azurecr.io/hello-world-app2:v14 .github/workflows
          docker push haritha123.azurecr.io/hello-world-app2:v14
          docker build -f mysql/Dockerfile -t haritha123.azurecr.io/hello-world-app:v13 .github/workflows
          docker push haritha123.azurecr.io/hello-world-app:v13
      
